### ISSUE TITLE
repeated slicing of ranges mishandled

### ISSUE THREAD

**Issue by josharian** [google/starlark-go#116]
```
$ starlark -c "print(range(3)[::2][:0][0])"
0
$ python2  -c "print(range(3)[::2][:0][0])"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
IndexError: list index out of range
$ python3  -c "print(range(3)[::2][:0][0])"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
IndexError: range object index out of range
```

This is an interesting bug. It appears (from the behavior) that it has to do with some hidden state in the range object or a compiler error:

```
$ starlark
Welcome to Starlark (go.starlark.net)
>>> range(3)
range(3)
>>> range(3)[::2]
range(0, 3, 2)
>>> range(3)[::2][:0]
range(0, 0, 2)
>>> range(3)[::2][:0][0]
0
>>> range(0, 0, 2)[0]
Traceback (most recent call last):
  <stdin>:1: in <expr>
Error: range index 0 out of range [0:0]
```

Note the difference in behavior between constructing `range(0, 0, 2)` via `range(3)[::2][:0]` vs spelling it directly as `range(0, 0, 2)`.

The same python3 session, for reference:

```
$ python3
Python 3.7.2 (default, Jan  8 2019, 11:26:15) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> range(3)
range(0, 3)
>>> range(3)[::2]
range(0, 3, 2)
>>> range(3)[::2][:0]
range(0, 0, 2)
>>> range(3)[::2][:0][0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: range object index out of range
>>> range(0, 0, 2)[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: range object index out of range
```

**Comment by josharian** [comment]
Simpler repro: `range(0, 0, 2)[:][0]`. This was a fun one.
