### ISSUE TITLE
unexpected global variable referenced before assignment

### ISSUE THREAD

**Issue by Pussbebe2103** [google/starlark-go#505]
Here's 2 scripts with -globalassign enabled, run the first one, and use its output as input/predeclared for the second one:

Script 1:

```py
hello = [123, 456]
debug = False
```

Script 2:

```py
print(hello)
```

It runs fine, but if you change the second script to:

```py
if debug:
    hello = "hello world"

print(hello)
```

It will throw an unexpected error: **global variable hello referenced before assignment**

Why?

**Comment by adonovan** [comment]
In Starlark and Python, within a function, an assignment statement creates a variable binding in the function, whether or not it is executed:

```
$ starlark
>>> def f():
...     if False:
...        x = 1
...     print(x)
... 
>>> f()
Traceback (most recent call last):
  <stdin>:1:2: in <expr>
  <stdin>:4:11: in f
Error: local variable x referenced before assignment
```

```
$ python3
>>> def f():
...    if False:
...      x = 1
...    print(x)
... 
>>> f()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in f
UnboundLocalError: cannot access local variable 'x' where it is not associated with a value
>>> 
```

But Starlark differs from Python in its treatment of the toplevel. The spec disallows loops and conditional assignments at toplevel (conditional assignments are just loops where n < 2!), and the -globalreassign flag in the Go implementation treats the toplevel like any other function.
